version: '3'

volumes:
  postgres_data: {}

services:
  flask:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - ./.envs/local/.postgres
      - ./.envs/local/.flask
    volumes:
      - .:/app
    command: /start
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 3
        window: 120s

  postgres:
    image: postgres:13.2
    volumes:
    - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - ./.envs/local/.postgres
    ports:
      - "5432:5432"