version: '3'

volumes:
  postgres_data: {}

services:
  flask:
    build:
      context: .
    depends_on:
      - postgres
    env_file:
      - ./.envs/local/.postgres
      - ./.envs/local/.flask
    volumes:
      - .:/app
    command: /start
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13.2
    env_file:
      - ./.envs/local/.postgres