"""add table of barcodes

Revision ID: 451bf6673954
Revises: af9ee2933239
Create Date: 2021-10-31 16:54:37.405576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '451bf6673954'
down_revision = 'af9ee2933239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_identifier',
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('identifiers', sa.String(length=100), nullable=False),
    sa.Column('identifier_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('food_id', 'identifiers', 'identifier_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_identifier')
    # ### end Alembic commands ###
